config/routes.rb
require "nested_form/engine"
require "nested_form/builder_mixin"


Rails.application.routes.draw do
  resources :tracers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: { sign_in: 'ログイン', sign_out: 'ログアウト'}

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  root to: 'welcome#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action :create, :read, :update, :destroy, to: :crud
    if user.has_role? :god
      can :manage, :all
    elsif user.has_role? :dosen
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :crud, :all
      cannot :crud, Role
    elsif user.has_role? :alumni
      cannot :access, :rails_admin
      can :read, :all
    end
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tracer.rb
class Tracer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    rescue_from CanCan::AccessDenied do |exception|
        redirect_to main_app.root_url
        flash[:error] = "You are not an admin"
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/tracers_controller.rb
class TracersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tracer, only: [:show, :edit, :update, :destroy]

  # GET /tracers
  # GET /tracers.json
  def index
    @tracers = Tracer.all

  end

  # GET /tracers/1
  # GET /tracers/1.json
  def show
  end

  # GET /tracers/new
  def new
    @tracer = Tracer.new
  end

  # GET /tracers/1/edit
  def edit
  end

  # POST /tracers
  # POST /tracers.json
  def create
    @tracer = Tracer.new(tracer_params)

    respond_to do |format|
      if @tracer.save
        format.html { redirect_to @tracer, notice: 'Tracer was successfully created.' }
        format.json { render :show, status: :created, location: @tracer }
      else
        format.html { render :new }
        format.json { render json: @tracer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracers/1
  # PATCH/PUT /tracers/1.json
  def update
    respond_to do |format|
      if @tracer.update(tracer_params)
        format.html { redirect_to @tracer, notice: 'Tracer was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracer }
      else
        format.html { render :edit }
        format.json { render json: @tracer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracers/1
  # DELETE /tracers/1.json
  def destroy
    @tracer.destroy
    respond_to do |format|
      format.html { redirect_to tracers_url, notice: 'Tracer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracer
      @tracer = Tracer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tracer_params
      params.require(:tracer).permit(:f21, :f22, :f23, :f24, :f25, :f26, :f27, :f301, :f302, :f303, :f401, :f402, :f403, :f404, :f405, :f406, :f407, :f408, :f409, :f410, :f411, :f412, :f413, :f414, :f415, :f501, :f502, :f503, :f6, :f7, :f7a, :f8, :f901, :f902, :f903, :f904, :f905, :f906, :f1001, :f1002, :f1101, :f1102, :f1201, :f1202, :f1301, :f1302, :f1303, :f14, :f15, :f1601, :f1602, :f1603, :f1604, :f1605, :f1606, :f1607, :f1608, :f1609, :f1610, :f1611, :f1612, :f1613, :f1614, :f1701, :f1702b, :f1703, :f1704b, :f1705, :f1706b, :f1705a, :f1706ba, :f1707, :f178b, :f1709, :f1710b, :f1711, :f1712b, :f1713, :f1714b, :f1715, :f1716b, :f1717, :f1718b, :f1719, :f1720b, :f1721, :f1722b, :f1723, :f1724b, :f1725, :f1726b, :f1727, :f1728b, :f1729, :f1730b, :f1731, :f1732b, :f1733, :f1734b, :f1735, :f1736b, :f1737, :f1738b, :f1737a, :f1738ba, :f1739, :f1740b, :f1741, :f1742b, :f1743, :f1744b, :f1745, :f1746b, :f1747, :f1748b, :f1749, :f1750b, :f1751, :f1752b, :f1753, :f1754b)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tracers_helper.rb
module TracersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<div class="site-header-container container">
	<div class="">
		<div class="">
			<header class="site-header">
        <div class="row py-3 align-items-center">
          <div class="col-lg-7 col-md-7">
            <div class="row align-items-center">
              <div class="col-lg-2 col-md-4 col-3">
                <div class="logo">
                  <a href="/site/index" title="CDC POLTEKPOS">
                    <%= active_link_to image_tag('logos/logo.png', alt:"Tracer Study POlTEKPOS", width:"72"), root_path, class:"navbar-brand" %>	
                  </a>
                </div>
              </div>
              <div class="col-lg-10 col-md-8 col-9">
                <div class="logo-desc-box">
                  <h2 class="m-0">TRACER STUDY </h2>
                  <h5 class="m-0 font-weight-bold">Politeknik Pos Indonesia</h5>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-5 col-md-5">
          <nav class="site-nav">					
            <ul class="main-menu">
              <li>
                <% if user_signed_in? %>
                <%= active_link_to 'logout' , destroy_user_session_path, method: :delete, class:"fe nav-link" %>
              </li>
            <li>
                <%= active_link_to "Edit Profile", edit_user_registration_path, class:"fe nav-link" %>
            </li>
            <li>
              <%= active_link_to "Survey Alumni", tracers_path, class:"fe nav-link" %>
            </li>
            <% else %>
            <li>
              <%= active_link_to 'login' , new_user_session_path, class:"fe nav-link" %>
            </li>
            <% end %>
            </ul>
        </nav>
        </div>
			</header>
		</div>
	</div>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TracerStudy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <style type='text/css'>
			.h {font-weight : bold ; vertical-align: top; color:red }
			.hl {font-size: 8px; font-weight : bold ; vertical-align: top; color:red }
			.i {font-weight : bold ; vertical-align: top; }
			.desc { display: none; }
		</style>
  </head>

  <body>
    <!-- header -->
    <%= render 'layouts/header' %>
    <div class="">

    <%= yield %>
    </div>
    <!--footer-->
    <%= render 'layouts/footer' %>
  
  </body>
</html>

app/views/tracers/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tracers</h1>
<div>
<table>
  <thead>
    <tr>
      <th>F21</th>
      <th>F22</th>
      <th>F23</th>
      <th>F24</th>
      <th>F25</th>
      <th>F26</th>
      <th>F27</th>
    </tr>
  </thead>
  <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f21 %></td>
        <td><%= tracer.f22 %></td>
        <td><%= tracer.f23 %></td>
        <td><%= tracer.f24 %></td>
        <td><%= tracer.f25 %></td>
        <td><%= tracer.f26 %></td>
        <td><%= tracer.f27 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F301</th>
      <th>F302</th>
      <th>F303</th>
    </tr>
  </thead>
  <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f301 %></td>
        <td><%= tracer.f302 %></td>
        <td><%= tracer.f303 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F401</th>
      <th>F402</th>
      <th>F403</th>
      <th>F404</th>
      <th>F405</th>
      <th>F406</th>
      <th>F407</th>
      <th>F408</th>
      <th>F409</th>
      <th>F410</th>
      <th>F411</th>
      <th>F412</th>
      <th>F413</th>
      <th>F414</th>
      <th>F415</th>
    </tr>
  </thead>
</table>
</div>
<div>
<table>
  <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f401 %></td>
        <td><%= tracer.f402 %></td>
        <td><%= tracer.f403 %></td>
        <td><%= tracer.f404 %></td>
        <td><%= tracer.f405 %></td>
        <td><%= tracer.f406 %></td>
        <td><%= tracer.f407 %></td>
        <td><%= tracer.f408 %></td>
        <td><%= tracer.f409 %></td>
        <td><%= tracer.f410 %></td>
        <td><%= tracer.f411 %></td>
        <td><%= tracer.f412 %></td>
        <td><%= tracer.f413 %></td>
        <td><%= tracer.f414 %></td>
        <td><%= tracer.f415 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F501</th>
      <th>F502</th>
      <th>F503</th>
    </tr>
  </thead>
    <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f501 %></td>
        <td><%= tracer.f502 %></td>
        <td><%= tracer.f503 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F6</th>
    </tr>
  </thead>
    <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f6 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F7</th>
      <th>F7a</th>
    </tr>
  </thead>
    <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f7 %></td>
        <td><%= tracer.f7a %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F8</th>
    </tr>
  </thead>
    <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f8 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F901</th>
      <th>F902</th>
      <th>F903</th>
      <th>F904</th>
      <th>F905</th>
      <th>F906</th>
    </tr>
  </thead>
  <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f901 %></td>
        <td><%= tracer.f902 %></td>
        <td><%= tracer.f903 %></td>
        <td><%= tracer.f904 %></td>
        <td><%= tracer.f905 %></td>
        <td><%= tracer.f906 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F1001</th>
      <th>F1002</th>
    </tr>
  </thead>
  <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f1001 %></td>
        <td><%= tracer.f1002 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F1101</th>
      <th>F1102</th>
    </tr>
  </thead>
    <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f1101 %></td>
        <td><%= tracer.f1102 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F1201</th>
      <th>F1202</th>
    </tr>
  </thead>
  <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f1201 %></td>
        <td><%= tracer.f1202 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F1301</th>
      <th>F1302</th>
      <th>F1303</th>
    </tr>
  </thead>
  <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f1301 %></td>
        <td><%= tracer.f1302 %></td>
        <td><%= tracer.f1303 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F14</th>
    </tr>
  </thead>
  <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f14 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F15</th>
    </tr>
  </thead>
    <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f15 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table> 
  <thead>
    <tr>
      <th>F1601</th>
      <th>F1602</th>
      <th>F1603</th>
      <th>F1604</th>
      <th>F1605</th>
      <th>F1606</th>
      <th>F1607</th>
      <th>F1608</th>
      <th>F1609</th>
      <th>F1610</th>
      <th>F1611</th>
      <th>F1612</th>
      <th>F1613</th>
      <th>F1614</th>
    </tr>
  </thead>
  <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f1601 %></td>
        <td><%= tracer.f1602 %></td>
        <td><%= tracer.f1603 %></td>
        <td><%= tracer.f1604 %></td>
        <td><%= tracer.f1605 %></td>
        <td><%= tracer.f1606 %></td>
        <td><%= tracer.f1607 %></td>
        <td><%= tracer.f1608 %></td>
        <td><%= tracer.f1609 %></td>
        <td><%= tracer.f1610 %></td>
        <td><%= tracer.f1611 %></td>
        <td><%= tracer.f1612 %></td>
        <td><%= tracer.f1613 %></td>
        <td><%= tracer.f1614 %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<table>
  <thead>
    <tr>
      <th>F1701</th>
      <th>F1702b</th>
      <th>F1703</th>
      <th>F1704b</th>
      <th>F1705</th>
      <th>F1706b</th>
      <th>F1705a</th>
      <th>F1706ba</th>
      <th>F1707</th>
      <th>F178b</th>
      <th>F1709</th>
      <th>F1710b</th>
      <th>F1711</th>
      <th>F1712b</th>
      <th>F1713</th>
      <th>F1714b</th>
      <th>F1715</th>
      <th>F1716b</th>
      <th>F1717</th>
      <th>F1718b</th>
      <th>F1719</th>
      <th>F1720b</th>
      <th>F1721</th>
      <th>F1722b</th>
      <th>F1723</th>
      <th>F1724b</th>
      <th>F1725</th>
      <th>F1726b</th>
      <th>F1727</th>
      <th>F1728b</th>
      <th>F1729</th>
      <th>F1730b</th>
      <th>F1731</th>
      <th>F1732b</th>
      <th>F1733</th>
      <th>F1734b</th>
      <th>F1735</th>
      <th>F1736b</th>
      <th>F1737</th>
      <th>F1738b</th>
      <th>F1737a</th>
      <th>F1738ba</th>
      <th>F1739</th>
      <th>F1740b</th>
      <th>F1741</th>
      <th>F1742b</th>
      <th>F1743</th>
      <th>F1744b</th>
      <th>F1745</th>
      <th>F1746b</th>
      <th>F1747</th>
      <th>F1748b</th>
      <th>F1749</th>
      <th>F1750b</th>
      <th>F1751</th>
      <th>F1752b</th>
      <th>F1753</th>
      <th>F1754b</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tracers.each do |tracer| %>
      <tr>
        <td><%= tracer.f1701 %></td>
        <td><%= tracer.f1702b %></td>
        <td><%= tracer.f1703 %></td>
        <td><%= tracer.f1704b %></td>
        <td><%= tracer.f1705 %></td>
        <td><%= tracer.f1706b %></td>
        <td><%= tracer.f1705a %></td>
        <td><%= tracer.f1706ba %></td>
        <td><%= tracer.f1707 %></td>
        <td><%= tracer.f178b %></td>
        <td><%= tracer.f1709 %></td>
        <td><%= tracer.f1710b %></td>
        <td><%= tracer.f1711 %></td>
        <td><%= tracer.f1712b %></td>
        <td><%= tracer.f1713 %></td>
        <td><%= tracer.f1714b %></td>
        <td><%= tracer.f1715 %></td>
        <td><%= tracer.f1716b %></td>
        <td><%= tracer.f1717 %></td>
        <td><%= tracer.f1718b %></td>
        <td><%= tracer.f1719 %></td>
        <td><%= tracer.f1720b %></td>
        <td><%= tracer.f1721 %></td>
        <td><%= tracer.f1722b %></td>
        <td><%= tracer.f1723 %></td>
        <td><%= tracer.f1724b %></td>
        <td><%= tracer.f1725 %></td>
        <td><%= tracer.f1726b %></td>
        <td><%= tracer.f1727 %></td>
        <td><%= tracer.f1728b %></td>
        <td><%= tracer.f1729 %></td>
        <td><%= tracer.f1730b %></td>
        <td><%= tracer.f1731 %></td>
        <td><%= tracer.f1732b %></td>
        <td><%= tracer.f1733 %></td>
        <td><%= tracer.f1734b %></td>
        <td><%= tracer.f1735 %></td>
        <td><%= tracer.f1736b %></td>
        <td><%= tracer.f1737 %></td>
        <td><%= tracer.f1738b %></td>
        <td><%= tracer.f1737a %></td>
        <td><%= tracer.f1738ba %></td>
        <td><%= tracer.f1739 %></td>
        <td><%= tracer.f1740b %></td>
        <td><%= tracer.f1741 %></td>
        <td><%= tracer.f1742b %></td>
        <td><%= tracer.f1743 %></td>
        <td><%= tracer.f1744b %></td>
        <td><%= tracer.f1745 %></td>
        <td><%= tracer.f1746b %></td>
        <td><%= tracer.f1747 %></td>
        <td><%= tracer.f1748b %></td>
        <td><%= tracer.f1749 %></td>
        <td><%= tracer.f1750b %></td>
        <td><%= tracer.f1751 %></td>
        <td><%= tracer.f1752b %></td>
        <td><%= tracer.f1753 %></td>
        <td><%= tracer.f1754b %></td>
        <td><%= link_to 'Show', tracer %></td>
        <td><%= link_to 'Edit', edit_tracer_path(tracer) %></td>
        <td><%= link_to 'Destroy', tracer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tracer', new_tracer_path %>

app/views/tracers/edit.html.erb
<h1>Editing Tracer</h1>

<%= render 'form', tracer: @tracer %>

<%= link_to 'Show', @tracer %> |
<%= link_to 'Back', tracers_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>